### ISSUE TITLE
[feature request] Possibility to choose from different substances

### ISSUE THREAD

**Issue by feinmann** [feinmann/sober#2]
* List for choosing different substances
* Possibility to enter consume-frequency
* Price-tags attached to substance-frequency to calculate the money-saved

**Comment by feinmann** [comment]
* Drop-down added to indicate substance....
Which choices should be included?

Former consume-frequency and money-related data still missing. Which should be included?

**Comment by h3llmann** [comment]
>* List for choosing different substances ...

@feinmann man könnte ne Datenbank mit Stoffpreisen anlegen die ja vom Ort abhängen und dann den Ort über ne API abfragen und so genauer ermitteln was man gespart hat. Dafür müsste man halt noch abfragen wie viel konsumiert wurde...

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by feinmann** [comment]
So eine Datenbank muss es doch schon geben, oder? Evtl könnte man auch im Darknet recherchieren. 

Aber eigentlich tendiere ich dazu, keine Raketenwissenschaft draus zu machen, und Durchschnittspreis anzugeben. Dann kann ja jeder selber noch korrigieren.

Konsumfrequenz muss man in jedem Fall angeben.

**Comment by h3llmann** [comment]
Ja, gibt es auch...man kann eine Möglichkeit schaffen dass Leute Preise angeben können-damit hätte man recht schnell eine gute Datenbank. Außerdem wäre gut wenn wir verschiedene Sprachen implementieren mit einem Dropdown rechts oben...

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by feinmann** [comment]
Ich würde es erstmal auf Englisch halten. Aber sowas kann man immer noch nachreichen. Dazu kannst dann einen eigenen Feature-Request-Issue aufmachen. Hab jetzt nicht so die Erfahrung mit multi-language... Aber da gibt es gute Lösungen.

**Comment by feinmann** [comment]
Added info about cost-savings, at the moment fixed value per substance.
